name: test
on:
 schedule:    
    - cron: "0 3 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install EPGGrabber
        run: npm install -g epg-grabber
      - name: Start grab.
        run: epg-grabber --config=jcom-config.js --days 3
